### ISSUE TITLE
Maximum execution time of 60 seconds exceeded

### ISSUE THREAD

**Issue by Davronjuraev** [Baizidmdashadzzaman/Laravel-zkteco-iclock9000-G-machine-attendance-system#1]
i'm getting this error, i'm connecting with true ip address, but loading some times and getting this one

**Comment by Davronjuraev** [comment]
when i'm adding this at top of request:
ini_set('max_execution_time', 300);

getting another error: unpack(): Type H: not enough input, need 1, have 0

btw ping going ok to device

**Comment by Baizidmdashadzzaman** [comment]
enable socket in you php.in . Check the ip in device and set your ip in project . it will work

**Comment by Davronjuraev** [comment]
But same thing, i do everything for connecting. Ip is correct, enabled my socket in php.ini
getting: Maximum execution time of 60 seconds exceeded. What i'm doing wrong then, please help

**Comment by Baizidmdashadzzaman** [comment]
Did you setup your device host information  option in device? you have to whitelist your server information in your device
